# Generated by Django 3.0.4 on 2020-12-24 14:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APNSDevice',
            fields=[
                ('apnsdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.APNSDevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.apnsdevice',),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('gcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.GCMDevice')),
                ('type', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.gcmdevice',),
        ),
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='notification')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='data')),
                ('mass', models.BooleanField(default=False, verbose_name='mass')),
                ('push_success', models.NullBooleanField(default=None, verbose_name='push success')),
                ('users', models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'Push message',
                'verbose_name_plural': 'Push messages',
            },
        ),
        migrations.CreateModel(
            name='FCMDeviceAndroid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('device.fcmdevice',),
        ),
        migrations.CreateModel(
            name='FCMDeviceIos',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('device.fcmdevice',),
        ),
    ]
