# Generated by Django 3.1.7 on 2021-06-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('gcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.gcmdevice')),
                ('type', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.gcmdevice',),
        ),
        migrations.CreateModel(
            name='FCMDeviceAndroid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('device.fcmdevice',),
        ),
        migrations.CreateModel(
            name='FCMDeviceIos',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('device.fcmdevice',),
        ),
    ]
