# Generated by Django 3.0.4 on 2021-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnsdevice',
            name='arcore',
            field=models.BooleanField(default=True, verbose_name='arcore'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='arcore',
            field=models.BooleanField(default=True, verbose_name='arcore'),
        ),
    ]
