# Generated by Django 3.1.7 on 2021-03-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210302_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushmessage',
            name='users',
        ),
        migrations.DeleteModel(
            name='APNSDevice',
        ),
        migrations.DeleteModel(
            name='PushMessage',
        ),
    ]
