# Generated by Django 3.1.7 on 2021-03-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210325_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevice',
            name='arcore',
        ),
    ]
