# Generated by Django 3.1.7 on 2021-04-06 17:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_userconfig_enable_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='error_notification_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=300)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=1200))]),
        ),
    ]
