# Generated by Django 3.1.7 on 2021-04-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_userconfig_error_notification_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='error_notification_interval',
        ),
    ]
