# Generated by Django 3.1.7 on 2021-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
