# Generated by Django 3.1.7 on 2021-04-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_clientalerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alert_type', models.PositiveSmallIntegerField(choices=[(0, 'Telegram')])),
                ('msg', models.TextField()),
                ('counter', models.PositiveSmallIntegerField(default=5)),
                ('enable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientAlerts',
        ),
    ]
