# Generated by Django 3.1.7 on 2021-09-24 10:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='monitor_type',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='error_notification_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600))]),
        ),
    ]
