# Generated by Django 3.1.7 on 2021-03-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorlog',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitor.monitor'),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='response_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
