# Generated by Django 3.2.7 on 2021-09-27 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20210924_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorlog',
            name='keyword',
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='is_successful',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
