# Generated by Django 3.1.7 on 2021-04-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210406_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='last_error_notification',
        ),
    ]
