# Generated by Django 3.1.7 on 2021-04-13 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_monitor_last_error_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='free_log_min_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='free_max_monitors',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pro_max_monitors',
            field=models.IntegerField(default=50),
        ),
    ]
