# Generated by Django 3.1.7 on 2021-04-14 13:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20210413_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='error_notification_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=300)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600))]),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='last_request',
            field=models.DateTimeField(),
        ),
    ]
