# Generated by Django 3.1.7 on 2021-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20210414_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='monitor',
            name='by_telegram',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
