# Generated by Django 3.1.7 on 2021-06-12 10:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20210517_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='max_timeout',
            field=models.DurationField(default=datetime.timedelta(seconds=10), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=30))]),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='free_log_min_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
